---
- name: Add OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  with_first_found:
      - files:
            - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
            - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
            - "{{ ansible_facts['distribution'] }}.yml"
            - "{{ ansible_facts['os_family'] }}.yml"
            - "{{ ansible_facts['system'] }}.yml"
            - "defaults.yml"
        paths:
            - "vars"
  loop_control:
      loop_var: loop_vars

- name: Install the Docker Compose packages
  ansible.builtin.include_tasks: packages.yml

- name: Manage the Docker Compose project
  ansible.builtin.include_tasks: compose.yml
