---
namespace: arillso
name: container
version: 1.0.1
readme: README.md

authors:
    - Simon Baerlocher (@sbaerlocher) <s.baerlocher@sbaerlocher.ch>
    - arillso (@arillso) <hello@arillso.io>

description: Ansible collection for container and orchestration management including Docker, Docker Compose, Kubernetes (K3s), Helm, Fleet, and Tailscale with comprehensive security hardening and GitOps support.

license:
    - MIT

tags:
    - container
    - apt
    - containerd
    - linux

dependencies:
    arillso.system: ">=0.0.17"
    community.docker: ">=3.4.11"

repository: https://github.com/arillso/ansible.container

documentation: https://guide.arillso.io/collections/arillso/container/index.html

homepage: https://arillso.io

issues: https://github.com/arillso/ansible.container/issues

build_ignore: []
