---
- name: Login to Docker registry
  become: true
  community.docker.docker_login:
    api_version: "{{ docker_login_api_version }}"
    ca_cert: "{{ docker_login_ca_cert }}"
    client_cert: "{{ docker_login_client_cert }}"
    client_key: "{{ docker_login_client_key }}"
    debug: "{{ docker_login_debug }}"
    docker_host: "{{ docker_login_docker_host }}"
    password: "{{ docker_login_password }}"
    reauthorize: "{{ docker_login_reauthorize }}"
    registry_url: "{{ docker_login_registry_url }}"
    ssl_version: "{{ docker_login_ssl_version }}"
    timeout: "{{ docker_login_timeout }}"
    tls: "{{ docker_login_tls }}"
    tls_hostname: "{{ docker_login_tls_hostname }}"
    tls_verify: "{{ docker_login_tls_verify }}"
    username: "{{ docker_login_username }}"
