---
argument_specs:
  main:
    short_description: Configure and manage Docker Compose environment using Ansible
    description:
      - This spec outlines parameters for configuring Docker Compose with Ansible.
      - It includes Docker Compose version, package names, directory paths, configuration methods, and project name.

    options:
      docker_compose_version:
        type: str
        description:
          - The desired Docker Compose version. Leave empty for the latest version.
        default: ""

      docker_compose_package:
        type: list
        elements: str
        description:
          - List of Docker Compose packages to install, appending the version if specified.
        default:
          - "{{ 'docker-compose-plugin=' + docker_compose_version if docker_compose_version != '' else 'docker-compose-plugin' }}"

      docker_compose_directory_path:
        type: str
        description:
          - Base path for Docker Compose configuration files.
        default: "/etc/docker/compose"

      docker_compose_directory:
        type: str
        description:
          - Full path to the Docker Compose project directory.
        default: "{{ docker_compose_directory_path }}/{{ docker_compose_project }}"

      docker_compose_use_file:
        type: bool
        description:
          - Flag to use a Docker Compose file (true) or inline configuration (false).
        default: true

      docker_compose_config:
        type: raw
        description:
          - Inline Docker Compose configuration, defined as a multi-line YAML string.
        default: []

      docker_compose_project:
        type: str
        description:
          - The name of the Docker Compose project, used in the full path construction.
        default: ""

      docker_compose_api_version:
        type: str
        description:
          - Docker API version to use, set to 'auto' for automatic version selection.
        default: "auto"

      docker_compose_build:
        type: bool
        description:
          - Option to build images before starting services.
        default: false

      docker_compose_ca_cert:
        type: str
        description:
          - Path to the CA certificate for server verification.
        default: null

      docker_compose_client_cert:
        type: str
        description:
          - Path to the client's TLS certificate for Docker communication.
        default: null

      docker_compose_client_key:
        type: str
        description:
          - Path to the client's TLS key for Docker communication.
        default: null

      docker_compose_debug:
        type: bool
        description:
          - Enable or disable debug mode.
        default: false

      docker_compose_dependencies:
        type: bool
        description:
          - Include or exclude linked services.
        default: true

      docker_compose_docker_host:
        type: str
        description:
          - Docker host URL or Unix socket path for API connection.
        default: "unix://var/run/docker.sock"

      docker_compose_env_file:
        type: str
        description:
          - Custom path to an environment file.
        default: null

      docker_compose_files:
        type: list
        elements: str
        description:
          - List of Compose file names to override the default docker-compose.yml.
        default: null

      docker_compose_hostname_check:
        type: bool
        description:
          - Check Docker daemon's hostname against client certificate.
        default: false

      docker_compose_nocache:
        type: bool
        description:
          - Control the use of cache during image build.
        default: false

      docker_compose_profiles:
        type: list
        elements: str
        description:
          - List of profiles to enable when starting services.
        default: null

      docker_compose_project_name:
        type: str
        description:
          - Custom name for the Docker Compose project.
        default: null

      docker_compose_pull:
        type: bool
        description:
          - Always pull images before starting the application.
        default: false

      docker_compose_recreate:
        type: str
        description: "Strategy for container recreation: 'always', 'never', or 'smart'."
        default: "smart"

      docker_compose_remove_images:
        type: str
        description:
          - Option to remove images when state is 'absent'.
        default: null

      docker_compose_remove_orphans:
        type: bool
        description:
          - Remove containers for services not defined in the Compose file.
        default: false

      docker_compose_remove_volumes:
        type: bool
        description:
          - Remove data volumes when state is 'absent'.
        default: false

      docker_compose_restarted:
        type: bool
        description:
          - Restart all containers when state is 'present'.
        default: false

      docker_compose_scale:
        type: dict
        description:
          - Dictionary defining service scaling.
        default: null

      docker_compose_services:
        type: list
        elements: str
        description:
          - List of specific services to operate on.
        default: null

      docker_compose_ssl_version:
        type: str
        description:
          - Specify a valid SSL version number for secure communication.
        default: null

      docker_compose_state:
        type: str
        description:
          - Desired state of the Docker Compose project.
        default: "present"

      docker_compose_stopped:
        type: bool
        description:
          - Stop all containers when state is 'present'.
        default: false

      docker_compose_timeout:
        type: int
        description:
          - Timeout in seconds for container shutdown operations.
        default: null

      docker_compose_tls:
        type: bool
        description:
          - Use TLS for API connection without verifying Docker host server's authenticity.
        default: false

      docker_compose_tls_hostname:
        type: str
        description:
          - Expected hostname of the Docker Host server for TLS verification.
        default: null

      docker_compose_use_ssh_client:
        type: bool
        description:
          - Flag to enable SSH client usage for Docker API communication.
        default: false

      docker_compose_validate_certs:
        type: bool
        description:
          - Verify the Docker host server's authenticity when using TLS.
        default: false
