---
galaxy_info:
    author: "arillso (@arillso)"
    description: "Logs into Docker registries on Debian, RedHat, and Ubuntu."
    license: MIT
    min_ansible_version: "2.15"
    platforms:
        - name: Debian
          versions:
              - bullseye
              - bookworm
        - name: Ubuntu
          versions:
              - jammy
              - noble
        - name: EL
          versions:
              - "8"
              - "9"

    galaxy_tags:
        - docker
        - login
        - registry
        - authentication
