---
galaxy_info:
    author: "arillso (@arillso)"
    description: "Installs and configures Docker Compose 2 on Debian, RedHat, and Ubuntu."
    license: MIT
    min_ansible_version: "2.15"
    platforms:
        - name: Debian
          versions:
              - bullseye
              - bookworm
        - name: Ubuntu
          versions:
              - jammy
              - noble
        - name: EL
          versions:
              - "8"
              - "9"

    galaxy_tags:
        - docker
        - compose
        - deployment
