---
- name: "Debian : ensure deb822 dependency"
  become: true
  ansible.builtin.apt:
      name: python3-debian
      state: present
      update_cache: true

- name: "Debian : remove legacy docker.list"
  become: true
  ansible.builtin.file:
      path: /etc/apt/sources.list.d/docker.list
      state: absent

- name: "Debian : add key"
  become: true
  ansible.builtin.get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /usr/share/keyrings/docker-archive-keyring.asc
      mode: "0644"
      force: true

- name: "Debian : add repository"
  become: true
  ansible.builtin.deb822_repository:
      name: docker
      types: deb
      architectures: amd64
      signed_by: /usr/share/keyrings/docker-archive-keyring.asc
      uris: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}"
      suites: "{{ ansible_facts['distribution_release'] }}"
      components: stable
      state: present
      enabled: true
  register: docker_repo

- name: "Debian : update apt cache"
  become: true
  ansible.builtin.apt:
      update_cache: true
  when: docker_repo is changed
